# Generated by Django 6.0.1 on 2026-01-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('STOCK', 'Action'), ('BOND', 'Obligation'), ('CRYPTO', 'Crypto-monnaie')], max_length=10, verbose_name="Type d'actif")),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'actif")),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Quantité')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Prix d'achat")),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Prix actuel')),
                ('purchase_date', models.DateField(verbose_name="Date d'achat")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actif',
                'verbose_name_plural': 'Actifs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'symbol', 'purchase_date')},
            },
        ),
    ]
